urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from . import views

urlpatterns = [
    # Examples:
    #url(r'^$', 'OpenDiet.views.home', name='home'),
    #url(r'^$', 'FitnessLog.views.fitness_form', name='log'),
    url(r'^$', views.fitness_form, name='log'),
    url(r'^(?P<page>\d+)$', views.fitness_form, name='log'),
    #url(r'^fitnesslog/$', views.fitness_form, name='log'),
    #url(r'^fitnesslog/(?P<page>\d+)$', views.fitness_form, name='log'),
    url(r'^overview', views.overview, name='overview'),
    url(r'^graph/$', views.graph, name='graph'),
    url(r'^graph/(?P<days>\d+)$', views.graph, name='graph'),
    url(r'^graph/(?P<username>\w+)$', views.graph, name='graph'),
    url(r'^graph/(?P<username>\w+)/(?P<days>\d+)$', views.graph, name='graph'),
    
    #url(r'^blog/', include('blog.urls')),
    #url(r'^login', 'OpenDiet.views.login_view'),
    #url(r'^logout', 'OpenDiet.views.logout_view'),
    #url(r'^register', 'OpenDiet.views.register', name='register'),
    #url(r'^userinfo/$','FitnessLog.views.userinfo_form', name='account' ),
    #url(r'^userinfo/(?P<username>\w+)$','FitnessLog.views.userinfo_form', name='account' ),
    #url(r'^register', 'OpenDiet.views.beta', name='register'),
    #url(r'^admin/', include(admin.site.urls)),
#    url(r'', include('social_auth.urls')),
]

models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import pprint
from decimal import Decimal, ROUND_UP
from numpy import polyfit

# Create your models here.
class FitnessLog(models.Model):
    user = models.ForeignKey(User)
    log_date = models.DateField(blank=False, null=False)
    weight = models.DecimalField(decimal_places=1, max_digits=4)
    trend = models.DecimalField(decimal_places=2, max_digits=5)
    body_fat = models.DecimalField(decimal_places=3, max_digits=3, default=0)
    note = models.TextField(blank=True)
    user_inputed = True

    def _get_lean_mass(self): 
        "Returns lean mass"
        if ( self.body_fat == 0.0 ):
            return "No Entry"
        return "%.2f" % ((1 - self.body_fat) * self.trend)
    lean_mass = property(_get_lean_mass)
    
    class Meta:
        ordering = ['user','log_date', 'weight', 'trend', 'body_fat' ]
        unique_together = ['user', 'log_date']
    
    def save(self, update_trend = False, *args, **kwargs):
        pp = pprint.PrettyPrinter(indent=4)
        pp.pprint("Save FitnessLog")
        if(self.body_fat>1):
            self.body_fat = self.body_fat
        try:
            yesterday = FitnessLog.objects.get( log_date = (self.log_date + datetime.timedelta(days=-1) ), user = self.user )
        # set yesterday to self if no yesterday
        except FitnessLog.DoesNotExist:
            # Check if there is a previous day and use that instead
            try:
                last_previous_day = FitnessLog.objects.filter( log_date__lt = self.log_date, user = self.user ).order_by('-log_date')[0:1].get()
                # fill in days here if update_trend = True
                yesterday = self.fill_entries(last_previous_day, self)[-1]
            # all else has failed, we are the first day, use self as yesterday
            except FitnessLog.DoesNotExist:
                yesterday = self
                self.trend = self.weight
        # Now that we have yesterday lets move on, we need to calculate the average using
        # An exponential running average with 10% smoothing
        self.trend = self.calc_trend(yesterday) 
        super(FitnessLog, self).save(*args, **kwargs)

        # if we should not update the trend we exit here
        if not update_trend:
            return

        # grab tomorrow
        tomorrow = self
        tomorrow_trend = Decimal("0.00")
        
        while not tomorrow_trend == tomorrow.trend :
            try:
                tomorrow = FitnessLog.objects.get( log_date = (tomorrow.log_date + datetime.timedelta(days=1) ), user = self.user )
            except FitnessLog.DoesNotExist:
                # check for future tomorrow
                try:
                    # if there is a future date call fill_entries
                    tomorrow = FitnessLog.objects.filter( log_date__gt = (tomorrow.log_date), user = self.user )[0:1].get()
                    # save future tomorrow, and exit
                    tomorrow.save( update_trend = True, *args, **kwargs)
                    return
                except FitnessLog.DoesNotExist:
                    return
            tomorrow_trend = tomorrow.trend.quantize(Decimal('.01'), rounding=ROUND_UP)
            tomorrow.save( *args, **kwargs)

    def delete(self, *args, **kwargs):
        # check if there is a next day
        try:
            tomorrow = FitnessLog.objects.filter( log_date__gt = self.log_date, user = self.user )[0:1].get()
            super(FitnessLog, self).delete(*args, **kwargs)
            tomorrow.save(update_trend=True)
        except FitnessLog.DoesNotExist:
            super(FitnessLog, self).delete(*args, **kwargs)

    def calc_trend(self, yesterday):
        todays_weight = self.weight
        yester_weight = yesterday.trend
        trend = Decimal(Decimal(0.1)*(todays_weight - yester_weight) + yester_weight)
        return trend.quantize(Decimal('.01'), rounding=ROUND_UP)

    def fill_entries(self, first_day, last_day):
        """Returns list of entries in between first_day and last_day"""
        logs = []
        weight_delta = last_day.weight - first_day.weight
        days = (last_day.log_date - first_day.log_date ).days
        increment = Decimal(weight_delta/days)
              
        # Begin filling in dates
        i=1
        while i < days:
            second_day = FitnessLog(log_date=(first_day.log_date + datetime.timedelta(days=i)), user = self.user)

            # To produce a smoother line use more decimal places on generated amounts
            second_day.user_inputed = False
            second_day.weight = (first_day.weight + (increment*i)).quantize(Decimal('.001'), rounding=ROUND_UP)
            if i == 1:
                second_day.trend = second_day.calc_trend(first_day)
            else :
                second_day.trend = second_day.calc_trend(logs[-1])
            i = i + 1
            logs.append(second_day)
        return logs

    def entries_between_dates(self, first_day, last_day):
        """Returns list of entries in between first_day and last_day using generated entries if need be"""
        days = ( last_day - first_day ).days
        
        entries = FitnessLog.objects.order_by('log_date').filter(user=self.user, log_date__gte = first_day, log_date__lte = last_day )
       
        # Now lets iterate through the list to verify that all dates are filled.
        yesterday = entries[0]
        logs = []
        for entry in entries:
            # First put in our current log
            if (entry.log_date - yesterday.log_date ).days > 1:
                logs.extend(yesterday.fill_entries(yesterday,entry))
            logs.append(entry)
            yesterday = entry
        
        #Check if days back lands between user-inputed days
        if len(logs) < (days + 1):
            #check for previous day with return of 1
            try:
                log = FitnessLog.objects.order_by('-log_date').filter(user=self.user, log_date__lt = first_day )[0:1].get()
            except FitnessLog.DoesNotExist:
                # If no previous days then we have all days possible
                pass
            # If there are previous days then calc and extract days - logs.count() and prepend to logs
            else:
                needed_days = (days - len(logs))
                temp_logs = log.fill_entries(log,logs[0])[:needed_days]
                temp_logs.extend(logs)
                logs = temp_logs

        return logs
    
    def calc_average(self, days):
        # Grab userinfo
        userinfo = UserInfo.objects.get(user=self.user)
        
        data = self.entries_between_dates( self.log_date - datetime.timedelta(days=days), self.log_date )
        if len(data) == 1:
            return {'weight_delta': 0, 'calories': 0, 'up_or_down': False}
        # get the best fit slope
        i = 0
        xdata = []
        ydata = []
        while i < len(data):
            xdata.append(i)
            ydata.append(float(data[i].trend))
            i=i+1
        temp = polyfit(x=xdata, y=ydata, deg=1)
        slope = temp[0]
        weight_delta = round(temp[0]*len(data),1)
        calories = abs(round(slope * (7716 if userinfo.metric else 3500 )))
        if weight_delta > 0:
            up_or_down = True
        else:
            up_or_down = False
            weight_delta = weight_delta * -1
        
        
        averages = {'weight_delta': weight_delta, 'calories': calories, 'up_or_down': up_or_down}
        
        return averages

class UserInfo(models.Model):
    user = models.OneToOneField("auth.User")
    metric = models.BooleanField(default='True')
    weight = models.DecimalField(decimal_places=1, max_digits=4, default=0.0)
    height = models.IntegerField(default=0.0)
    birthday = models.DateField(null=True, blank=True, default=None)
    public = models.BooleanField(default='True')
    beta = models.BooleanField(default='False')

templates/FitnessLog/fitnesslog.html
{% extends "base.html" %}
{% load pagination %}
{% load percentage %}
{% block meta_title %}Log{% endblock %}
{% block main %}
<form action="/fitnesslog/" method="post" class="form-horizontal" role="form">
	{% csrf_token %}
	<div class="form-group">
		<label for="inputDate" class="col-lg-1 control-label">Date</label>
		<div class="col-lg-2">
			<input type="date" class="form-control" id="inputDate" name="log_date" value="{{ next_date|date:"Y-m-d" }}" \>
		</div><!-- col -->
		<label for="inputWeight" class="col-lg-1 control-label">Weight</label>
		<div class="col-lg-2">
			<input type="number" class="form-control" id="inputWeight" name="weight" value="{{last_weight}}" min="0" step="0.1" \>
		</div><!-- col -->
		<label for="inputBodyFat" class="col-lg-1 control-label">Body Fat%</label>
		<div class="col-lg-2">
			<input type="number" class="form-control" id="inputBodyFat" name="body_fat" value="{{last_body_fat|percent}}" min="0" step="0.1" \>
		</div><!-- col -->
		<label for="inputNote" class="col-lg-1 control-label">Note</label>
		<div class="col-lg-2">
			<input type="text" class="form-control" id="inputNote" name="note" \>
		</div><!-- col -->
		<div class="col-lg-2">
			<button type="submit" name="add-entry" value="Submit" class="btn btn-primary">Submit</button>
		</div>
	</div><!-- form-group -->
</form>
<div class="panel panel-default">
<div class="table-responsive">
<table class="table table-striped">
	<tr>
		<th>Date</th>
		<th>Weight</th>
		<th>Avg Weight</th>
		<th>Body Fat %</th>
{% if user.is_staff %}
                <th>Lean Mass</th>
{% endif %}
		<th>Note</th>
		<th>Delete</th>
	</tr>
{% for entry in log %}
 <form action="/fitnesslog/" method="post">
 {% csrf_token %}
 <input type="hidden" name="id" value={{ entry.id }} />
 <tr>
 <td>{{ entry.log_date }}</td>
 <td>{{ entry.weight }}</td>
 <td>{{ entry.trend }}</td>
 <td>{{ entry.body_fat|percentage }}</td>
{% if user.is_staff %}
 <td>{{ entry.lean_mass }}</td>
{% endif %}
 <td>{{ entry.note }}</td>
 <td><button type="submit" name="delete" value="Delete">Delete</button></td>
 </tr>
 </form>
{% endfor %}
</table>
</div><!--Responsive Table-->
<div class="row">
<div class="col-md-12 text-center">
<ul class="pagination pagination-sm">
{% if current_page.number == 1 %}
  <li class="disabled"><a href="/fitnesslog/1">|&laquo;</a></li>
{% else %}
  <li><a href="/fitnesslog/1">&laquo;&laquo;</a></li>
{% endif %}
{% if current_page.has_previous %}
  <li><a href="/fitnesslog/{{ current_page.previous_page_number }}">&laquo;</a></li>
{% else %}
  <li class="disabled"><a href="/fitnesslog/{{ current_page.number }}">&laquo;</a></li>
{% endif %}
{% paginate_pages pages current_page.number as paginated_pages %}
{% for page in paginated_pages %}
{%if page == current_page.number%}
  <li class="active disabled"><a href="/fitnesslog/{{page}}">{{page}}</a></li>
{%else%} 
  <li><a href="/fitnesslog/{{page}}">{{page}}</a></li>
{% endif %}
{% endfor %}
{% if current_page.has_next %}
  <li><a href="/fitnesslog/{{ current_page.next_page_number }}">&raquo;</a></li>
{% else %}
  <li class="disabled"><a href="/fitnesslog/{{current_page.number}}" disabled=true>&raquo;</a></li>
{% endif %}
{% if current_page.number == pages.num_pages %}
  <li class="disabled"><a href="/fitnesslog/{{pages.num_pages}}">&raquo;&raquo;</a></li>
{% else %}
  <li><a href="/fitnesslog/{{pages.num_pages}}">&raquo;|</a></li>
{% endif %}
</ul>
</div>
</div>
</div><!--Panel-->
{% endblock %}

templates/FitnessLog/graph.html
{% extends "base.html" %}
{% block meta_title %}Graph{% endblock %}
{% block extra_css %}
<link href="/static/css/custom.css" rel="stylesheet" media="screen">
{% endblock %}
{% block main %}
<h3>{{ error }}</h3>
<a href="{{username}}/7">7 Days</a> |
<a href="{{username}}/30">30 Days</a> |
<a href="{{username}}/90">90 Days</a> |
<a href="{{username}}/365">Year</a> |
<a href="{{username}}/9000">All</a>
<br/><input type='checkbox' name='lean_mass' checked='checked' id='lm'></input><label for='lm'>Show Lean Mass</label>
<div id="placeholder" style="width:100%;height:800px"></div>
<p>Weight Change For Period: <span class="weight-change"></span>{{ metric|yesno:"kg,lbs" }} Caloric Defecit: <span class="defecit"></span>
<!-- Graph data -->
<!-- Flot -->
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/static/public/flot/excanvas.min.js"></script><![endif]-->
<script language="javascript" type="text/javascript" src="/static/public/flot/jquery.js"></script>
<script language="javascript" type="text/javascript" src="/static/public/flot/jquery.flot.js"></script>
<script language="javascript" type="text/javascript" src="/static/public/flot/jquery.flot.threshold.js"></script>
<script language="javascript" type="text/javascript" src="/static/public/flot/jquery.flot.time.js"></script>
<script language="javascript" type="text/javascript" src="/static/public/flot/jquery.flot.fillbetween.js"></script>
<script language="javascript" type="text/javascript" src="/static/public/flot/jquery.flot.resize.js"></script>
<script language="javascript" type="text/javascript" src="/static/public/date.js"></script>
<script language="javascript" type="text/javascript" src="/static/js/graph.js"></script>
<script type="text/javascript">
var input=[
{% for entry in log %}['{{ entry.log_date|date:"n/d/Y" }}', {{ entry.weight }}, {{ entry.trend}}, {{ entry.body_fat }}, {{ entry.user_inputed|yesno:"true,false" }} ],
{% endfor %}

];
plotData(input,{{ metric|yesno:"1,0" }});
</script>
<script src="http://code.jquery.com/jquery.js"></script>	

{% endblock %}

templates/FitnessLog/no_log_data.html
{% extends "base.html" %}
{% block title %} - Home{% endblock %}
{% block content %}
<h1>Weight Loss Overview</h1>
<div class="well well-lg">
<table class="table large-font">
	<thead>
		<tr>
			<th></th>
			<th>Weight Change</th>
			<th>Calorie Defecit / Excess</th>
			<th>Estimated Goal Date</th>
		</tr>
	</thead>
	<tbody>
		<th>
			<td colspan="4">At least one entry is required before the Overview will work.  Try adding today's weight to your <a href="/fitnesslog/">Fitness Log.</a></td>
		</th>
	</tbody>
</table>
</div><!-- well -->
{% endblock %}

templates/FitnessLog/overview.html
{% extends "base.html" %}
{% block meta_title %}Overview{% endblock %}
{% block main %}
<h1>Weight Loss Overview</h1>
<div class="well well-lg">
<table class="table large-font">
	<thead>
		<tr>
			<th></th>
			<th>Weight Change</th>
			<th>Calorie Defecit / Excess</th>
			<th>Estimated Goal Date</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th><a href="graph/{{user.username}}/7">7 Days</a></th>
			<td class="{{ day_7.up_or_down|yesno:"bad,good"}}"><span class="glyphicon glyphicon-arrow-{{ day_7.up_or_down|yesno:"up,down"}}"></span>
			{{ day_7.weight_delta}} {{ metric|yesno:"Kg,Lbs" }}
			</td>
			
			<td class="{{ day_7.up_or_down|yesno:"bad,good"}}"><span class="glyphicon glyphicon-arrow-{{ day_7.up_or_down|yesno:"up,down"}}"></span>
			{{ day_7.calories}}
			</td>
			
			<td>Coming Soon</td>
		</tr>
		<tr>
			<th><a href="graph/{{user.username}}/30">30 Days</a></th>
			<td class="{{ day_30.up_or_down|yesno:"bad,good"}}"><span class="glyphicon glyphicon-arrow-{{ day_30.up_or_down|yesno:"up,down"}}"></span>
			{{ day_30.weight_delta}} {{ metric|yesno:"Kg,Lbs" }}
			</td>
			
			<td class="{{ day_30.up_or_down|yesno:"bad,good"}}"><span class="glyphicon glyphicon-arrow-{{ day_30.up_or_down|yesno:"up,down"}}"></span>
			{{ day_30.calories}}
			</td>
			
			<td>Coming Soon</td>
		</tr>	
		<tr>
			<th><a href="graph/{{user.username}}/90">90 Days</a></th>
			<td class="{{ day_90.up_or_down|yesno:"bad,good"}}"><span class="glyphicon glyphicon-arrow-{{ day_90.up_or_down|yesno:"up,down"}}"></span>
			{{ day_90.weight_delta}} {{ metric|yesno:"Kg,Lbs" }}
			</td>
			
			<td class="{{ day_90.up_or_down|yesno:"bad,good"}}"><span class="glyphicon glyphicon-arrow-{{ day_90.up_or_down|yesno:"up,down"}}"></span>
			{{ day_90.calories}}
			</td>
			
			<td>Coming Soon</td>
		</tr>
	</tbody>
</table>
</div><!-- well -->
{% endblock %}

templates/FitnessLog/user_account.html
{% extends "base.html" %}
{% block content %}
<form action="/userinfo/{{user.username}}" method="post" class="form-vertical" role="form">
	{% csrf_token %}
	<table class="form-group">
<tr>
 <th><label for="id_username">Username:</label></th>
 <td><span id="id_username">{{user.username}}</span></td>
</tr>
<tr>
 <th><label for="id_metric">Metric:</label></th>
 <td><input {% if form.metric.value %}checked="True"{%endif%} id="id_metric" name="metric" type="checkbox" /></td>
 <td>{{ form.metric.errors }}</td>
</tr>
<tr>
 <th><label for="id_weight">Goal Weight:</label></th>
 <td><input id="id_weight" name="weight" type="text" value="{{form.weight.value}}" /></td>
 <td>{{ form.weight.errors}}</td>
</tr>
<tr>
 <th><label for="id_height">Height:</label></th>
 <td><input id="id_height" name="height" type="text" value="{{form.height.value}}" /></td>
 <td>{{ form.height.errors}}</td>
</tr>
<tr>
 <th><label for="id_birthday">Birthday (optional):</label></th>
 <td><input id="id_birthday" name="birthday" type="date" value="{{form.birthday.value|date:"Y-m-d"}}" /></td>
 <td>{{ form.birthday.errors}}</td>
</tr>
<tr>
 <th><label for="id_public">Public:</label></th>
 <td><input {% if form.public.value %}checked="True"{%endif%} id="id_public" name="public" type="checkbox" /></td>
 <td>{{ form.public.errors}}</td>
</tr>
		<div class="col-lg-2">
			<button type="submit" name="add-entry" value="Submit" class="btn btn-primary">Update</button>
		</div>
	</table><!-- form-group -->
</form>
{% endblock %}

templates/FitnessLog/user_profile.html
{% extends base.html %}
{% block content %}
{% end block %}